<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use DateTime;

class MapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('maps')->insert([
            [
                'location_id' => 1,
                'store_name' => '田舎館駅',
                'address' => '〒038-1111 青森県南津軽郡田舎館村高樋宮本',
                'gourmet' => null,
                'keyword' => 'ABCが作った？',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 1,
                'store_name' => 'かねちゃん',
                'address' => '〒038-1113 青森県南津軽郡田舎館村田舎舘中辻１３３−７',
                'gourmet' => 'どんこラーメン',
                'keyword' => '田んぼアートがすごい',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 1,
                'store_name' => '創作料理　御幸',
                'address' => '〒036-0377 青森県黒石市中町３６',
                'gourmet' => 'つゆやきそば',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 1,
                'store_name' => '青森県田舎館村',
                'address' => '青森県田舎館村',
                'gourmet' => null,
                'keyword' => '食わしすぎ',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 1,
                'store_name' => '食処ふじた',
                'address' => '〒036-0357 青森県黒石市追子野木３丁目４７０−１',
                'gourmet' => '焼きそば',
                'keyword' => '焼きそば番組か',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 1,
                'store_name' => '鳥文食堂',
                'address' => '〒038-1133 青森県南津軽郡田舎館村大根子松森１６９−８',
                'gourmet' => '焼きそば',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 2,
                'store_name' => '長崎県五島列島',
                'address' => '長崎県五島列島',
                'gourmet' => null,
                'keyword' => 'せいじの移動　せいじにギャラはやらん',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 2,
                'store_name' => '平安食堂',
                'address' => '〒853-0015 長崎県五島市東浜町１丁目１０−１５',
                'gourmet' => null,
                'keyword' => '長崎丸出しの食堂やで',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 2,
                'store_name' => '一登',
                'address' => '〒853-0007 長崎県五島市福江町１２−１',
                'gourmet' => null,
                'keyword' => 'せいじに下品と言われたくない大悟',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 2,
                'store_name' => 'ビッグヒライパワーセンター店',
                'address' => '〒853-0041 長崎県五島市籠淵町２１６３',
                'gourmet' => '五島うどん',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 2,
                'store_name' => '鬼岳',
                'address' => '〒853-0013長崎県五島市上大津町2873-1',
                'gourmet' => null,
                'keyword' => 'もうないで',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 2,
                'store_name' => '奥浦海鮮直売所',
                'address' => '〒853-0053 長崎県五島市奥浦町２１５３',
                'gourmet' => 'クエのしゃぶしゃぶ　キビナゴの刺身',
                'key_word' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 3,
                'store_name' => '沖島漁業会館',
                'address' => '〒523-0801 滋賀県近江八幡市沖島町４３',
                'gourmet' => null,
                'keyword' => '三輪車に乗り、うまく運転できない',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 3,
                'store_name' => '汀の精',
                'address' => '〒523-0801 滋賀県近江八幡市沖島町３４６−２５',
                'gourmet' => null,
                'keyword' => 'かたせとおじいちゃんの会話が成立しない',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 3,
                'store_name' => '沖島小学校',
                'address' => '〒523-0801 滋賀県近江八幡市沖島町３６０',
                'gourmet' => null,
                'keyword' => 'シンプルに薄しぃ',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 3,
                'store_name' => 'いっぷくどう',
                'address' => '〒523-0801 滋賀県近江八幡市沖島町２４３',
                'gourmet' => '豚汁',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 4,
                'store_name' => '頴娃駅',
                'address' => '〒891-0701 鹿児島県南九州市頴娃町郡',
                'gourmet' => null,
                'keyword' => '頴でえいと読み、娃は読まない',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 4,
                'store_name' => '招福そば',
                'address' => '〒891-0702 鹿児島県南九州市頴娃町牧之内３９６５',
                'gourmet' => 'ざるそば',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 4,
                'store_name' => 'ばあば亭',
                'address' => '〒891-0702 鹿児島県南九州市頴娃町牧之内１４４０',
                'gourmet' => 'ランチ',
                'keyword' => '暇ですることない人が自分の家食堂にしたんや',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 4,
                'store_name' => 'えい中央温泉センター',
                'address' => '〒891-0702 鹿児島県南九州市頴娃町牧之内２８９０',
                'gourmet' => null,
                'keyword' => 'せいじのブラジリアン',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 4,
                'store_name' => '居酒屋　勇気凛々',
                'address' => '〒891-0701 鹿児島県南九州市頴娃町郡９２１３−４',
                'gourmet' => 'ビール',
                'keyword' => 'せいじの失言2　せいじの立ちション',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 5,
                'store_name' => '大寅屋',
                'address' => '〒879-0628 大分県豊後高田市新町９９２',
                'gourmet' => 'ちゃんぽん',
                'keyword' => '具志堅のウソ1東京 具志堅の子供嫌い 具志堅のウソ2大阪',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 5,
                'store_name' => '大分県豊後高田市昭和の町',
                'address' => '大分県豊後高田市昭和の町',
                'gourmet' => null,
                'keyword' => '具志堅花むしりとる　7個例えよ　具志堅沖縄に染みる',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 5,
                'store_name' => 'cafe CACHE*CACHE',
                'address' => '〒879-0628 大分県豊後高田市大字新町８９９',
                'gourmet' => null,
                'keyword' => 'ガールズバーあります？',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 6,
                'store_name' => '禄剛崎',
                'address' => '〒927-1441 石川県珠洲市禄剛崎',
                'gourmet' => null,
                'keyword' => 'うそくさいナダル1',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 6,
                'store_name' => 'いかなてて',
                'address' => '〒927-1441 石川県珠洲市狼煙町７０−１',
                'gourmet' => '焼きあごだしわかめうどん',
                'keyword' => 'うそくさいお世辞 2度と会えないでしょう',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 6,
                'store_name' => '石川県珠洲市狼煙町',
                'address' => '石川県珠洲市狼煙町',
                'gourmet' => null,
                'keyword' => 'ナダルの奇行と怖い顔 ナダルの失礼 大根食って、スイカの皮みたい うそくさいナダル２',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 6,
                'store_name' => 'つばき茶屋',
                'address' => '〒927-1446 石川県珠洲市折戸町１−３−１',
                'gourmet' => 'イカさま定食',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 6,
                'store_name' => 'ゴジラ岩',
                'address' => '〒927-1304 石川県珠洲市馬緤町６',
                'gourmet' => null,
                'keyword' => 'ちっちゃいな',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 6,
                'store_name' => '平家の里',
                'address' => '〒927-1322 石川県珠洲市長橋町13-17-2 珠洲製塩内',
                'gourmet' => '一九二蕎麦',
                'keyword' => 'お父さんを悪人に仕立てるナダル',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 7,
                'store_name' => '長野県高山村',
                'address' => '長野県高山村',
                'gourmet' => null,
                'keyword' => '大吾の倒し方　アルファード１　アルファード２',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 7,
                'store_name' => '子安そば　文の蔵',
                'address' => '〒382-0821 長野県上高井郡高山村牧１３３６',
                'gourmet' => '天ざる',
                'keyword' => 'フォローがない武井壮 全員馬鹿',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 7,
                'store_name' => 'ふじたや酒店',
                'address' => '〒382-0821 長野県上高井郡高山村牧１６５５−３',
                'gourmet' => 'ナッチョ',
                'keyword' => 'ロングコートの武井壮 カツアゲする武井壮',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 7,
                'store_name' => '山田温泉大湯',
                'address' => '〒382-0816 長野県上高井郡高山村山田温泉３５８０',
                'gourmet' => null,
                'keyword' => 'モザイクが薄しぃ テレビ離れが加速する',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 7,
                'store_name' => '食彩酒房　鼓',
                'address' => '〒382-0800 長野県上高井郡高山村高井３２２４−１１',
                'gourmet' => null,
                'keyword' => '美女の前で脱ぐ武井壮',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 8,
                'store_name' => '宝亭',
                'address' => '〒100-1511 東京都八丈島八丈町三根７６５',
                'gourmet' => null,
                'keyword' => 'おもろない',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 8,
                'store_name' => '裏見ヶ滝温泉',
                'address' => '〒100-1623 東京都 八丈島八丈町中之郷１２４６',
                'gourmet' => null,
                'keyword' => 'ププッピドゥー',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 9,
                'store_name' => '伊計ビーチ',
                'address' => '〒904-2421 沖縄県うるま市与那城伊計４０５',
                'gourmet' => '沖縄そば',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 9,
                'store_name' => '沖縄県うるま市浜比嘉島',
                'address' => '沖縄県うるま市浜比嘉島',
                'gourmet' => null,
                'keyword' => '一発15万やから',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 9,
                'store_name' => 'エスパシオ',
                'address' => '〒904-2425 沖縄県うるま市与那城桃原１３５−１',
                'gourmet' => 'アイスコーヒー',
                'keyword' => null,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 9,
                'store_name' => '沖縄県うるま市宮城島',
                'address' => '沖縄県うるま市宮城島',
                'gourmet' => 'バナナ',
                'keyword' => '相席たばこ　砂になりたい',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 10,
                'store_name' => 'さるふつ丸ごと館',
                'address' => '北海道宗谷郡猿払村 村浜鬼志別214',
                'gourmet' => 'もりそば　かきあげ　アイスクリーム',
                'keyword' => 'そこはなに？　怖がられる長州　帰ってもいいですか？',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 10,
                'store_name' => '北海道猿払村',
                'address' => '北海道猿払村',
                'gourmet' => 'ソフトほたて貝柱8粒　ビール',
                'keyword' => '相席していーい？　食ってみな飛ぶぞ　凄いね　お前たち!　マジで飲んだぁ　バラァ',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 10,
                'store_name' => '円丁牧場',
                'address' => '〒098-6225北海道猿払村（宗谷郡）宗谷郡猿払村芦野2162-14',
                'gourmet' => '牛乳',
                'key_word' => '臭うな　牛の最後までのクソ　長州締めロング',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 11,
                'store_name' => '三重県鳥羽市答志島',
                'address' => '三重県鳥羽市答志島',
                'gourmet' => null,
                'keyword' => '連続殺人',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 11,
                'store_name' => 'まるみつ寿司',
                'address' => '〒517-0002 三重県鳥羽市答志町１１０６',
                'gourmet' => '上にぎり　めかぶの三杯酢　めかぶのみそ汁',
                'keyword' => '独特の目薬の差し方　ノブはデブタレント　記憶なくしょーんか',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 12,
                'store_name' => '御食事処　はましん',
                'address' => '〒701-3204 岡山県備前市日生町日生２４１−３０',
                'gourmet' => '穴子のひつまぶし',
                'keyword' => '難しいボケ',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 12,
                'store_name' => 'とんかつ　かつ平',
                'address' => '〒701-3204 岡山県備前市日生町日生２４６−４０',
                'gourmet' => 'ヒレカツ定食',
                'keyword' => '気まずい',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 12,
                'store_name' => 'CAFE RAD',
                'address' => '〒701-3204 岡山県備前市日生町日生６４１−４７',
                'gourmet' => 'ホットコーヒー　シフォンケーキ',
                'keyword' => 'しぽーん',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 12,
                'store_name' => 'きたろう',
                'address' => '〒701-3204 岡山県備前市日生町日生２４１−１７',
                'gourmet' => 'スープ焼きそば',
                'keyword' => 'のどちんこキュッキュ',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
            [
                'location_id' => 12,
                'store_name' => 'たぬき山展望台',
                'address' => '〒701-3204 岡山県備前市日生町日生',
                'gourmet' => null,
                'keyword' => 'アーメマ',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
                'deleted_at' => null,
            ],
        ]);
    }
}
